services:
  db:
    image: postgres:17-alpine
    container_name: mdd
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=mdd
    ports:
      - "${DATABASE_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
